apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: practice-dpl
  name: practice-dpl
spec:
  replicas: 8
  selector:
    matchLabels:
      app: practice-dpl
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: practice-dpl
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
