apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: practice-dpl
  name: practice-dpl
spec:
  replicas: 8
  selector:
    matchLabels:
      app: practice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: practice
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v2.7.1
        name: practice-mealie
        resources: {}
status: {}
