apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: practice
  name: practice
spec:
  ports:
  - name: "9000"
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: practice
  type: LoadBalancer
status:
  loadBalancer: {}
