apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: example-pod
  name: example-pod
spec:
  containers:
  - image: nginx
    name: example-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
