apiVersion: v1
kind: Service
metadata:
  name: sftp-service
  namespace: netvault
spec:
  selector:
    app: sftp
  type: NodePort
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30222